# Generated by Django 4.2.4 on 2023-12-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Profile_pic',
            new_name='profile_pic',
        ),
    ]
