# Generated by Django 4.2.4 on 2023-12-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_rename_profile_pic_userprofile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Slider/')),
            ],
        ),
    ]
