# Generated by Django 4.2.4 on 2023-12-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_sliderimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderImg',
        ),
    ]
